### ISSUE TITLE
Installation do not finish properly - cannot start x11 or box86/64

### ISSUE THREAD

**Issue by JonJonesBR** [Ilya114/Box64Droid#1]
The installation in my device did not complete. It keeps in a 3 dot screen. If i force close and try start x11 or box86/64 it returns a error. My device: poco F3 6 GB ram ROM Stock MIUI 14 snapdragon 870.

![Screenshot_2023-05-02-12-10-29-172_com termux](https://user-images.githubusercontent.com/68039931/235710972-2b7a7a22-c74c-4555-9836-9bc5280afcaf.jpg)

![Screenshot_2023-05-02-12-18-16-324_com termux](https://user-images.githubusercontent.com/68039931/235710982-0215cf0c-1f48-4816-8800-8f44c94e9aa8.jpg)

**Comment by stredohori1** [comment]
Type start-box

**Comment by Ilya114** [comment]
Fixed

**Comment by JonJonesBR** [comment]
Thanks for the answer my friend. It is still not working with any of the commands, but very good project.

**Comment by JonJonesBR** [comment]
The installation completes but any of the commands are working. Tried all. Could be the version of Android? I am using 13.
